global:
  scrape_interval: 15s

scrape_configs:
  - job_name: iris-http
    metrics_path: /metrics
    static_configs:
      - targets: ["iris-api:8000"]

  - job_name: iris-security
    metrics_path: /metrics/iris
    static_configs:
      - targets: ["iris-api:8000"]
